name: Release

on:
  push:
    tags:
      - v**

permissions:
  contents: write

jobs:
  draft_release:
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - name: Draft release
        id: draft_release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
      - name: Set upload url
        run: |
          echo "upload_url=${{ steps.draft_release.outputs.upload_url }}" >> "$GITHUB_ENV"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: draft_release
    strategy:
      matrix:
        arch: ["amd64", "arm64"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.mod

      - uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ matrix.arch }}-go-${{ hashFiles('go.sum', '*/go.sum') }}
          restore-keys: |
            ${{ matrix.arch }}-go

      - name: Build
        run: |
          GOOS=linux GOARCH=${{ matrix.arch }} go build cmd/main.go -o bin/ouraring-exporter

      - name: Zip
        run: zip ouraring-exporter.zip bin/ouraring-exporter

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1
