name: Release

on:
  push:
    tags:
      - v**

permissions:
  contents: write

jobs:
  draft_release:
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - name: Draft release
        id: draft_release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
      - name: Set upload url
        run: |
          echo "release_id=${{ steps.draft_release.outputs.id }}" >> "$GITHUB_ENV"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: draft_release
    strategy:
      matrix:
        arch: ["amd64", "arm64"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.mod

      - uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ matrix.arch }}-go-${{ hashFiles('go.sum', '*/go.sum') }}
          restore-keys: |
            ${{ matrix.arch }}-go

      - name: Build
        run: |
          GOOS=linux GOARCH=${{ matrix.arch }} go build -o bin/ouraring-exporter cmd/main.go

      - name: Zip
        run: zip ouraring-exporter.zip bin/ouraring-exporter

      - name: Upload
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/tetsuya28/ouraring-exporter/releases/${{ env.release_id }}/assets?name=linux-${{ matrix.arc }}/ouraring-exporter.zip" \
            -f '@ouraring-exporter.zip'
